---
# handlers file for apache2

- name: start apache2
  service:
    name: "{{ apache2_service_name }}"
    state: started

- name: stop apache2
  service:
    name: "{{ apache2_service_name }}"
    state: stopped

- name: restart apache2
  service:
    name: "{{ apache2_service_name }}"
    state: restarted

- name: reload apache2
  service:
    name: "{{ apache2_service_name }}"
    state: reloaded
